# ------------------
# Travis CI settings
# ------------------
# Test changes of this .travis.yml config before submitting them:
# https://lint.travis-ci.org
# ---------------------------------------------------------------

language: android

jdk: oraclejdk8

android:
  components:
  - tools
  - android-23
  - build-tools-23.0.2
  - extra-android-m2repository

script: ./gradlew assembleDebug check

after_success:
  - "export SHORT_HASH=$(echo $TRAVIS_COMMIT | head -c 8)"
  - "export FILENAME=soundboard-snapshot-${SHORT_HASH}.apk"
  - "cp app/build/outputs/apk/app-debug.apk ${FILENAME}"
  - "curl -F filedata=@${FILENAME} https://meonwax.de/soundboard/releases/"
